apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1g24
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0054-tenant/tkwch-fix-0075-0054-app/devfile-sample-1g24@sha256:98f7de0a49fecf1d98a023b936de0f79a15edf81127ca3aadcee07f33b502b0a
        name: my-nodejs
        resources: {}
status: {}
